version: '3'
services:
    mongo_db:
        hostname: mongo_db
        container_name: mongo_db
        image: mongo:latest
        restart: always
        # command:
        #     - '-f'
        #     - '/etc/mongod.conf'
        # volumes:
        #     - './docker/mongod.conf:/etc/mongod.conf'
        #     - '/mongo/data:/data/db'
        ports:
            - '27017:27017'
    node:
        build: 
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: node
        restart: always
        links:
            - mongo_db
        depends_on:
            - mongo_db
        ports:
            - '8080:8080'
        command:
            ["./wait-for-it.sh","mongo_db:27017", "--", "pm2-runtime", "start", "pm2-docker.json"]